#!/usr/bin/env python3
"""Apply a board profile to the Brookesia work tree (#260).

setup.sh copies the generic overlay into the work tree, then calls this to patch
the profile-owned values on top. Base overlay values for the patched fields are
don't-cares -- the profile wins. See profiles/README.md for the field map.

    python3 apply_profile.py <profile-name> [--work <brookesia-dir>]

Default work dir: $BROOKESIA_DIR or ~/esp/esp-brookesia. Patches are idempotent.
"""
import argparse
import json
import os
import re
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))


def die(msg):
    print(f"apply_profile: ERROR: {msg}", file=sys.stderr)
    sys.exit(1)


def patch_shell_desktop_bg(work, color):
    """resource/shell/styles/shell.json -> shell.desktop.bgColor."""
    p = os.path.join(work, "system/brookesia_system_super/resource/shell/styles/shell.json")
    if not os.path.isfile(p):
        die(f"shell.json not found at {p}")
    if color is None:
        print("  desktopBg: null -> leaving upstream token default")
        return
    t = open(p).read()
    # replace the bgColor line inside the "shell.desktop" block only
    pat = re.compile(r'("shell\.desktop"\s*:\s*\{[^}]*?"bgColor"\s*:\s*)"[^"]*"', re.S)
    new, n = pat.subn(rf'\1"{color}"', t)
    if n != 1:
        die(f"could not patch shell.desktop.bgColor (matched {n} times) in {p}")
    open(p, "w").write(new)
    print(f"  shell.desktop.bgColor -> {color}")


def patch_launcher(work, launcher):
    """resource/shell/constants/portrait.json -> launcher* geometry constants."""
    p = os.path.join(work, "system/brookesia_system_super/resource/shell/constants/portrait.json")
    if not os.path.isfile(p):
        die(f"portrait.json not found at {p}")
    t = open(p).read()
    mapping = {
        "launcherColumns": ("columns", int),
        "launcherGridWidth": ("gridWidth", str),
        "launcherItemWidth": ("itemWidth", str),
        "launcherItemHeight": ("itemHeight", str),
        "launcherItemGap": ("itemGap", str),
        "launcherIconTileSize": ("iconTileSize", str),
        "launcherIconSize": ("iconSize", str),
    }
    for key, (pkey, typ) in mapping.items():
        if pkey not in launcher:
            continue
        val = launcher[pkey]
        if typ is int:
            repl = str(int(val))
            pat = re.compile(rf'("{key}"\s*:\s*)\d+')
        else:
            repl = f'"{val}"'
            pat = re.compile(rf'("{key}"\s*:\s*)"[^"]*"')
        t, n = pat.subn(rf'\g<1>{repl}', t)
        if n < 1:
            die(f"could not patch {key} in {p}")
    open(p, "w").write(t)
    print(f"  launcher grid -> {launcher.get('columns')} cols "
          f"({launcher.get('itemWidth')} x {launcher.get('itemHeight')})")


def patch_apps(work, apps):
    """main/CMakeLists.txt -> TUNASTREET_APP_PACKAGES list."""
    p = os.path.join(work, "examples/system/super/main/CMakeLists.txt")
    if not os.path.isfile(p):
        die(f"CMakeLists.txt not found at {p}")
    t = open(p).read()
    block = "set(TUNASTREET_APP_PACKAGES\n" + "".join(f"    {a}\n" for a in apps) + ")"
    pat = re.compile(r"set\(TUNASTREET_APP_PACKAGES.*?\)", re.S)
    new, n = pat.subn(lambda _m: block, t, count=1)
    if n != 1:
        die(f"could not patch TUNASTREET_APP_PACKAGES in {p}")
    open(p, "w").write(new)
    print(f"  apps -> {', '.join(apps)}")


def copy_splash(work, prof_dir, splash):
    dst = os.path.join(work, "system/brookesia_system_super/resource/startup/images/background.png")
    src = os.path.join(prof_dir, splash)
    if not os.path.isfile(src):
        print(f"  splash: {src} not present -> leaving overlay background.png "
              f"(fill this profile's splash to override)")
        return
    shutil.copyfile(src, dst)
    print(f"  splash -> {os.path.relpath(src, HERE)}")


def write_header(work, prof):
    """Generated main/board_profile.h consumed by main.cpp + shell_app_launcher.cpp."""
    p = os.path.join(work, "examples/system/super/main/board_profile.h")
    hide = 1 if prof.get("launcher", {}).get("hideFiles") else 0
    evict = prof.get("wifi", {}).get("evictAp", "")
    c2 = prof.get("c2", {}).get("baseUrl", "")
    body = (
        "// GENERATED by apply_profile.py -- do not edit. Board profile: "
        f"{prof['name']}\n"
        "#pragma once\n"
        f"#define BOARD_PROFILE_NAME \"{prof['name']}\"\n"
        f"#define BOARD_HIDE_FILES {hide}\n"
        f"#define BOARD_WIFI_EVICT_AP \"{evict}\"\n"
        f"#define BOARD_C2_BASE_URL \"{c2}\"\n"
    )
    open(p, "w").write(body)
    print(f"  board_profile.h -> HIDE_FILES={hide} EVICT_AP='{evict}' C2='{c2}'")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("profile")
    ap.add_argument("--work", default=os.environ.get("BROOKESIA_DIR",
                    os.path.expanduser("~/esp/esp-brookesia")))
    args = ap.parse_args()

    prof_dir = os.path.join(HERE, "profiles", args.profile)
    prof_path = os.path.join(prof_dir, "profile.json")
    if not os.path.isfile(prof_path):
        die(f"no such profile: {prof_path}")
    prof = json.load(open(prof_path))
    work = args.work
    if not os.path.isdir(work):
        die(f"work tree not found: {work}")

    print(f"apply_profile: '{prof['name']}' -> {work}")
    patch_shell_desktop_bg(work, prof.get("brand", {}).get("desktopBg"))
    copy_splash(work, prof_dir, prof.get("splash", "background.png"))
    patch_launcher(work, prof.get("launcher", {}))
    patch_apps(work, prof.get("apps", []))
    write_header(work, prof)
    print("apply_profile: done")


if __name__ == "__main__":
    main()
